import type { BodyFocus, DiscomfortArea, EquipmentAccess, ExercisePrescription, WeakPoint } from "@/lib/types";

export type MovementPattern =
  | "squat"
  | "hinge"
  | "lunge"
  | "horizontal-push"
  | "vertical-push"
  | "horizontal-pull"
  | "vertical-pull"
  | "isolation"
  | "anti-extension"
  | "anti-rotation"
  | "carry"
  | "power"
  | "conditioning";

export type ExerciseEquipment =
  | EquipmentAccess
  | "cable"
  | "barbell"
  | "machine"
  | "kettlebell"
  | "band";

export type ExerciseTemplate = Omit<
  ExercisePrescription,
  | "sets"
  | "reps"
  | "rest"
  | "equipment"
  | "substitution"
  | "targetRir"
  | "targetRpe"
  | "tempo"
  | "stimulusToFatigue"
  | "progressionRule"
  | "adaptation"
  | "rationale"
  | "supersetWith"
  | "safetyNote"
> & {
  equipment: ExerciseEquipment;
  focus: BodyFocus[];
  primaryTargets: WeakPoint[];
  secondaryTargets: WeakPoint[];
  movementPattern: MovementPattern;
  stabilityDemand: 1 | 2 | 3 | 4 | 5;
  fatigueScore: 1 | 2 | 3 | 4 | 5;
  difficulty: 1 | 2 | 3;
  setupComplexity: 1 | 2 | 3 | 4 | 5;
  crowdingFriendliness: 1 | 2 | 3 | 4 | 5;
  jointStress: Partial<Record<"shoulder" | "elbow" | "wrist" | "lower-back" | "knee" | "hip", 1 | 2 | 3 | 4 | 5>>;
  substituteOptions: string[];
  substitutionGroup: string;
  contraindications: DiscomfortArea[];
  saferFor: DiscomfortArea[];
  hypertrophyRating: 1 | 2 | 3 | 4 | 5;
  strengthRating: 1 | 2 | 3 | 4 | 5;
  athleticRating: 1 | 2 | 3 | 4 | 5;
  setupZone: "rack" | "bench" | "dumbbell" | "cable" | "machine" | "floor" | "open-space";
};

function exercise(template: ExerciseTemplate): ExerciseTemplate {
  return template;
}

export const exerciseLibrary: ExerciseTemplate[] = [
  exercise({
    name: "Back squat",
    muscleGroup: "legs",
    primaryTargets: ["legs"],
    secondaryTargets: ["glutes", "core"],
    equipment: "barbell",
    focus: ["lower", "full-body"],
    movementPattern: "squat",
    stabilityDemand: 4,
    fatigueScore: 5,
    difficulty: 3,
    setupComplexity: 5,
    crowdingFriendliness: 1,
    jointStress: { knee: 3, hip: 3, "lower-back": 3 },
    contraindications: ["legs", "glutes", "back"],
    saferFor: [],
    substitutionGroup: "squat",
    hypertrophyRating: 5,
    strengthRating: 5,
    athleticRating: 4,
    setupZone: "rack",
    cue: "Brace before the descent, keep pressure through the whole foot, and stop before reps grind.",
    substituteOptions: ["Goblet squat", "Leg press", "Tempo bodyweight squat"]
  }),
  exercise({
    name: "Goblet squat",
    muscleGroup: "legs",
    primaryTargets: ["legs"],
    secondaryTargets: ["glutes", "core"],
    equipment: "dumbbells-only",
    focus: ["lower", "full-body"],
    movementPattern: "squat",
    stabilityDemand: 2,
    fatigueScore: 2,
    difficulty: 1,
    setupComplexity: 1,
    crowdingFriendliness: 5,
    jointStress: { knee: 2, hip: 2 },
    contraindications: ["legs"],
    saferFor: ["back"],
    substitutionGroup: "squat",
    hypertrophyRating: 4,
    strengthRating: 2,
    athleticRating: 2,
    setupZone: "dumbbell",
    cue: "Stay tall, keep the weight close, and leave the last rep clean.",
    substituteOptions: ["Tempo bodyweight squat", "Split squat hold", "Step-up"]
  }),
  exercise({
    name: "Leg press",
    muscleGroup: "legs",
    primaryTargets: ["legs"],
    secondaryTargets: ["glutes"],
    equipment: "machine",
    focus: ["lower", "full-body"],
    movementPattern: "squat",
    stabilityDemand: 1,
    fatigueScore: 3,
    difficulty: 1,
    setupComplexity: 2,
    crowdingFriendliness: 2,
    jointStress: { knee: 3, hip: 2 },
    contraindications: ["legs"],
    saferFor: ["back"],
    substitutionGroup: "squat",
    hypertrophyRating: 5,
    strengthRating: 3,
    athleticRating: 1,
    setupZone: "machine",
    cue: "Control the lower, keep hips heavy on the pad, and do not lock out aggressively.",
    substituteOptions: ["Goblet squat", "Step-up", "Tempo bodyweight squat"]
  }),
  exercise({
    name: "Tempo bodyweight squat",
    muscleGroup: "legs",
    primaryTargets: ["legs"],
    secondaryTargets: ["glutes"],
    equipment: "bodyweight",
    focus: ["lower", "full-body", "conditioning"],
    movementPattern: "squat",
    stabilityDemand: 1,
    fatigueScore: 1,
    difficulty: 1,
    setupComplexity: 1,
    crowdingFriendliness: 5,
    jointStress: { knee: 1, hip: 1 },
    contraindications: [],
    saferFor: ["back", "shoulders"],
    substitutionGroup: "squat",
    hypertrophyRating: 2,
    strengthRating: 1,
    athleticRating: 2,
    setupZone: "floor",
    cue: "Use a three-second lower and stand up with control.",
    substituteOptions: ["Chair squat", "Split squat hold", "Step-up"]
  }),
  exercise({
    name: "Trap bar deadlift",
    muscleGroup: "glutes",
    primaryTargets: ["glutes"],
    secondaryTargets: ["legs", "back", "core"],
    equipment: "barbell",
    focus: ["lower", "full-body"],
    movementPattern: "hinge",
    stabilityDemand: 3,
    fatigueScore: 5,
    difficulty: 3,
    setupComplexity: 4,
    crowdingFriendliness: 1,
    jointStress: { "lower-back": 4, hip: 3 },
    contraindications: ["back", "glutes", "legs"],
    saferFor: [],
    substitutionGroup: "hinge",
    hypertrophyRating: 4,
    strengthRating: 5,
    athleticRating: 4,
    setupZone: "open-space",
    cue: "Push the floor away, keep lats tight, and finish tall without leaning back.",
    substituteOptions: ["Dumbbell Romanian deadlift", "Hip thrust", "Glute bridge"]
  }),
  exercise({
    name: "Dumbbell Romanian deadlift",
    muscleGroup: "glutes",
    primaryTargets: ["glutes"],
    secondaryTargets: ["legs", "back"],
    equipment: "dumbbells-only",
    focus: ["lower", "full-body"],
    movementPattern: "hinge",
    stabilityDemand: 2,
    fatigueScore: 3,
    difficulty: 2,
    setupComplexity: 1,
    crowdingFriendliness: 5,
    jointStress: { "lower-back": 2, hip: 2 },
    contraindications: ["back", "glutes"],
    saferFor: ["shoulders"],
    substitutionGroup: "hinge",
    hypertrophyRating: 5,
    strengthRating: 3,
    athleticRating: 3,
    setupZone: "dumbbell",
    cue: "Hinge back, feel hamstrings load, and keep the spine quiet.",
    substituteOptions: ["Glute bridge", "Single-leg hip hinge", "Hip thrust"]
  }),
  exercise({
    name: "Hip thrust",
    muscleGroup: "glutes",
    primaryTargets: ["glutes"],
    secondaryTargets: ["legs", "core"],
    equipment: "barbell",
    focus: ["lower", "full-body"],
    movementPattern: "hinge",
    stabilityDemand: 2,
    fatigueScore: 3,
    difficulty: 2,
    setupComplexity: 4,
    crowdingFriendliness: 2,
    jointStress: { hip: 2, "lower-back": 1 },
    contraindications: ["glutes"],
    saferFor: ["back", "shoulders"],
    substitutionGroup: "glute-bridge",
    hypertrophyRating: 5,
    strengthRating: 4,
    athleticRating: 2,
    setupZone: "bench",
    cue: "Lock ribs down and squeeze at the top without overextending.",
    substituteOptions: ["Glute bridge", "Dumbbell Romanian deadlift", "Single-leg hip hinge"]
  }),
  exercise({
    name: "Glute bridge",
    muscleGroup: "glutes",
    primaryTargets: ["glutes"],
    secondaryTargets: ["core"],
    equipment: "bodyweight",
    focus: ["lower", "full-body"],
    movementPattern: "hinge",
    stabilityDemand: 1,
    fatigueScore: 1,
    difficulty: 1,
    setupComplexity: 1,
    crowdingFriendliness: 5,
    jointStress: { hip: 1, "lower-back": 1 },
    contraindications: [],
    saferFor: ["back", "legs", "shoulders"],
    substitutionGroup: "glute-bridge",
    hypertrophyRating: 2,
    strengthRating: 1,
    athleticRating: 1,
    setupZone: "floor",
    cue: "Exhale first, tuck ribs down, and squeeze glutes without arching.",
    substituteOptions: ["Hip thrust", "Single-leg hip hinge", "Tempo bodyweight squat"]
  }),
  exercise({
    name: "Walking lunge",
    muscleGroup: "legs",
    primaryTargets: ["legs"],
    secondaryTargets: ["glutes", "core"],
    equipment: "dumbbells-only",
    focus: ["lower", "conditioning", "full-body"],
    movementPattern: "lunge",
    stabilityDemand: 4,
    fatigueScore: 3,
    difficulty: 2,
    setupComplexity: 2,
    crowdingFriendliness: 3,
    jointStress: { knee: 3, hip: 2 },
    contraindications: ["legs", "glutes"],
    saferFor: ["back"],
    substitutionGroup: "single-leg",
    hypertrophyRating: 4,
    strengthRating: 2,
    athleticRating: 4,
    setupZone: "open-space",
    cue: "Step long enough to control the knee and push through the whole foot.",
    substituteOptions: ["Reverse lunge", "Step-up", "Split squat hold"]
  }),
  exercise({
    name: "Step-up",
    muscleGroup: "legs",
    primaryTargets: ["legs"],
    secondaryTargets: ["glutes", "core"],
    equipment: "dumbbells-only",
    focus: ["lower", "conditioning", "full-body"],
    movementPattern: "lunge",
    stabilityDemand: 3,
    fatigueScore: 2,
    difficulty: 1,
    setupComplexity: 2,
    crowdingFriendliness: 4,
    jointStress: { knee: 2, hip: 2 },
    contraindications: ["legs"],
    saferFor: ["back"],
    substitutionGroup: "single-leg",
    hypertrophyRating: 3,
    strengthRating: 2,
    athleticRating: 4,
    setupZone: "dumbbell",
    cue: "Own the top position before stepping back down.",
    substituteOptions: ["Reverse lunge", "Tempo bodyweight squat", "Marching high knees"]
  }),
  exercise({
    name: "Machine chest press",
    muscleGroup: "chest",
    primaryTargets: ["chest"],
    secondaryTargets: ["shoulders", "arms"],
    equipment: "machine",
    focus: ["push", "upper", "full-body"],
    movementPattern: "horizontal-push",
    stabilityDemand: 1,
    fatigueScore: 2,
    difficulty: 1,
    setupComplexity: 2,
    crowdingFriendliness: 2,
    jointStress: { shoulder: 2, elbow: 1 },
    contraindications: ["chest", "shoulders"],
    saferFor: ["back"],
    substitutionGroup: "horizontal-press",
    hypertrophyRating: 5,
    strengthRating: 3,
    athleticRating: 1,
    setupZone: "machine",
    cue: "Press smoothly and keep shoulder blades anchored.",
    substituteOptions: ["Dumbbell floor press", "Push-up", "Incline push-up"]
  }),
  exercise({
    name: "Barbell bench press",
    muscleGroup: "chest",
    primaryTargets: ["chest"],
    secondaryTargets: ["shoulders", "arms"],
    equipment: "barbell",
    focus: ["push", "upper", "full-body"],
    movementPattern: "horizontal-push",
    stabilityDemand: 4,
    fatigueScore: 4,
    difficulty: 3,
    setupComplexity: 4,
    crowdingFriendliness: 1,
    jointStress: { shoulder: 3, elbow: 2, wrist: 2 },
    contraindications: ["chest", "shoulders"],
    saferFor: [],
    substitutionGroup: "horizontal-press",
    hypertrophyRating: 4,
    strengthRating: 5,
    athleticRating: 3,
    setupZone: "bench",
    cue: "Stack wrists over elbows, keep shoulder blades set, and stop two reps before form changes.",
    substituteOptions: ["Dumbbell floor press", "Machine chest press", "Push-up"]
  }),
  exercise({
    name: "Incline dumbbell press",
    muscleGroup: "chest",
    primaryTargets: ["chest"],
    secondaryTargets: ["shoulders", "arms"],
    equipment: "dumbbells-only",
    focus: ["push", "upper", "full-body"],
    movementPattern: "horizontal-push",
    stabilityDemand: 3,
    fatigueScore: 3,
    difficulty: 2,
    setupComplexity: 2,
    crowdingFriendliness: 4,
    jointStress: { shoulder: 3, elbow: 2 },
    contraindications: ["chest", "shoulders"],
    saferFor: ["back"],
    substitutionGroup: "horizontal-press",
    hypertrophyRating: 5,
    strengthRating: 4,
    athleticRating: 2,
    setupZone: "dumbbell",
    cue: "Use a low incline, keep elbows slightly tucked, and press without shoulder glide.",
    substituteOptions: ["Dumbbell floor press", "Push-up", "Machine chest press"]
  }),
  exercise({
    name: "Dumbbell floor press",
    muscleGroup: "chest",
    primaryTargets: ["chest"],
    secondaryTargets: ["arms"],
    equipment: "dumbbells-only",
    focus: ["push", "upper", "full-body"],
    movementPattern: "horizontal-push",
    stabilityDemand: 2,
    fatigueScore: 2,
    difficulty: 1,
    setupComplexity: 1,
    crowdingFriendliness: 5,
    jointStress: { shoulder: 1, elbow: 1 },
    contraindications: ["chest"],
    saferFor: ["shoulders", "back"],
    substitutionGroup: "horizontal-press",
    hypertrophyRating: 4,
    strengthRating: 3,
    athleticRating: 1,
    setupZone: "floor",
    cue: "Pause lightly on the floor and drive with control.",
    substituteOptions: ["Push-up", "Incline push-up", "Machine chest press"]
  }),
  exercise({
    name: "Push-up",
    muscleGroup: "chest",
    primaryTargets: ["chest"],
    secondaryTargets: ["shoulders", "arms", "core"],
    equipment: "bodyweight",
    focus: ["push", "upper", "full-body"],
    movementPattern: "horizontal-push",
    stabilityDemand: 3,
    fatigueScore: 2,
    difficulty: 1,
    setupComplexity: 1,
    crowdingFriendliness: 5,
    jointStress: { shoulder: 2, wrist: 2 },
    contraindications: ["chest", "shoulders"],
    saferFor: ["back"],
    substitutionGroup: "horizontal-press",
    hypertrophyRating: 3,
    strengthRating: 2,
    athleticRating: 3,
    setupZone: "floor",
    cue: "Keep ribs stacked and stop before the shoulders drift forward.",
    substituteOptions: ["Incline push-up", "Dumbbell floor press", "Machine chest press"]
  }),
  exercise({
    name: "One-arm dumbbell row",
    muscleGroup: "back",
    primaryTargets: ["back"],
    secondaryTargets: ["arms", "core"],
    equipment: "dumbbells-only",
    focus: ["pull", "upper", "full-body"],
    movementPattern: "horizontal-pull",
    stabilityDemand: 2,
    fatigueScore: 2,
    difficulty: 1,
    setupComplexity: 1,
    crowdingFriendliness: 5,
    jointStress: { "lower-back": 1, elbow: 1 },
    contraindications: ["back"],
    saferFor: ["shoulders"],
    substitutionGroup: "row",
    hypertrophyRating: 5,
    strengthRating: 3,
    athleticRating: 2,
    setupZone: "dumbbell",
    cue: "Pull elbow toward the hip and avoid twisting through the torso.",
    substituteOptions: ["Chest-supported dumbbell row", "Backpack row", "Seated cable row"]
  }),
  exercise({
    name: "Chest-supported dumbbell row",
    muscleGroup: "back",
    primaryTargets: ["back"],
    secondaryTargets: ["arms"],
    equipment: "dumbbells-only",
    focus: ["pull", "upper", "full-body"],
    movementPattern: "horizontal-pull",
    stabilityDemand: 1,
    fatigueScore: 2,
    difficulty: 1,
    setupComplexity: 2,
    crowdingFriendliness: 4,
    jointStress: { "lower-back": 1, shoulder: 1 },
    contraindications: ["back"],
    saferFor: ["back", "shoulders"],
    substitutionGroup: "row",
    hypertrophyRating: 5,
    strengthRating: 3,
    athleticRating: 2,
    setupZone: "dumbbell",
    cue: "Let the bench support you and pull with elbows, not momentum.",
    substituteOptions: ["One-arm dumbbell row", "Backpack row", "Seated cable row"]
  }),
  exercise({
    name: "Seated cable row",
    muscleGroup: "back",
    primaryTargets: ["back"],
    secondaryTargets: ["arms"],
    equipment: "cable",
    focus: ["pull", "upper", "full-body"],
    movementPattern: "horizontal-pull",
    stabilityDemand: 1,
    fatigueScore: 2,
    difficulty: 1,
    setupComplexity: 2,
    crowdingFriendliness: 3,
    jointStress: { shoulder: 1, elbow: 1 },
    contraindications: ["back"],
    saferFor: ["back"],
    substitutionGroup: "row",
    hypertrophyRating: 5,
    strengthRating: 3,
    athleticRating: 1,
    setupZone: "cable",
    cue: "Finish with shoulder blades in your back pockets.",
    substituteOptions: ["One-arm dumbbell row", "Chest-supported dumbbell row", "Backpack row"]
  }),
  exercise({
    name: "Lat pulldown",
    muscleGroup: "back",
    primaryTargets: ["back"],
    secondaryTargets: ["arms"],
    equipment: "machine",
    focus: ["pull", "upper", "full-body"],
    movementPattern: "vertical-pull",
    stabilityDemand: 1,
    fatigueScore: 2,
    difficulty: 1,
    setupComplexity: 2,
    crowdingFriendliness: 2,
    jointStress: { shoulder: 2, elbow: 1 },
    contraindications: ["back", "shoulders"],
    saferFor: [],
    substitutionGroup: "vertical-pull",
    hypertrophyRating: 5,
    strengthRating: 3,
    athleticRating: 2,
    setupZone: "machine",
    cue: "Drive elbows down and stop before the shoulders roll forward.",
    substituteOptions: ["Band pulldown", "Inverted row", "One-arm dumbbell row"]
  }),
  exercise({
    name: "Pull-up",
    muscleGroup: "back",
    primaryTargets: ["back"],
    secondaryTargets: ["arms", "core"],
    equipment: "bodyweight",
    focus: ["pull", "upper", "full-body"],
    movementPattern: "vertical-pull",
    stabilityDemand: 4,
    fatigueScore: 4,
    difficulty: 3,
    setupComplexity: 2,
    crowdingFriendliness: 3,
    jointStress: { shoulder: 3, elbow: 2 },
    contraindications: ["back", "shoulders", "arms"],
    saferFor: [],
    substitutionGroup: "vertical-pull",
    hypertrophyRating: 4,
    strengthRating: 5,
    athleticRating: 4,
    setupZone: "open-space",
    cue: "Start each rep from the back, then drive elbows toward your ribs.",
    substituteOptions: ["Lat pulldown", "Band pulldown", "Inverted row"]
  }),
  exercise({
    name: "Band pulldown",
    muscleGroup: "back",
    primaryTargets: ["back"],
    secondaryTargets: ["arms"],
    equipment: "bodyweight",
    focus: ["pull", "upper", "full-body"],
    movementPattern: "vertical-pull",
    stabilityDemand: 1,
    fatigueScore: 1,
    difficulty: 1,
    setupComplexity: 1,
    crowdingFriendliness: 5,
    jointStress: { shoulder: 1, elbow: 1 },
    contraindications: [],
    saferFor: ["shoulders", "arms"],
    substitutionGroup: "vertical-pull",
    hypertrophyRating: 2,
    strengthRating: 1,
    athleticRating: 1,
    setupZone: "open-space",
    cue: "Pull elbows toward ribs and keep neck relaxed.",
    substituteOptions: ["Inverted row", "One-arm dumbbell row", "Lat pulldown"]
  }),
  exercise({
    name: "Dumbbell shoulder press",
    muscleGroup: "shoulders",
    primaryTargets: ["shoulders"],
    secondaryTargets: ["arms", "core"],
    equipment: "dumbbells-only",
    focus: ["push", "upper", "full-body"],
    movementPattern: "vertical-push",
    stabilityDemand: 3,
    fatigueScore: 3,
    difficulty: 2,
    setupComplexity: 1,
    crowdingFriendliness: 5,
    jointStress: { shoulder: 4, elbow: 2, "lower-back": 2 },
    contraindications: ["shoulders", "back"],
    saferFor: [],
    substitutionGroup: "vertical-press",
    hypertrophyRating: 4,
    strengthRating: 4,
    athleticRating: 3,
    setupZone: "dumbbell",
    cue: "Press in a slight arc and keep ribs stacked over hips.",
    substituteOptions: ["Landmine press", "Lateral raise", "Incline push-up"]
  }),
  exercise({
    name: "Landmine press",
    muscleGroup: "shoulders",
    primaryTargets: ["shoulders"],
    secondaryTargets: ["chest", "arms", "core"],
    equipment: "barbell",
    focus: ["push", "upper", "full-body"],
    movementPattern: "vertical-push",
    stabilityDemand: 2,
    fatigueScore: 2,
    difficulty: 1,
    setupComplexity: 3,
    crowdingFriendliness: 2,
    jointStress: { shoulder: 2, elbow: 1 },
    contraindications: ["shoulders"],
    saferFor: ["shoulders", "back"],
    substitutionGroup: "vertical-press",
    hypertrophyRating: 4,
    strengthRating: 3,
    athleticRating: 3,
    setupZone: "open-space",
    cue: "Press forward and up without shrugging into the neck.",
    substituteOptions: ["Dumbbell shoulder press", "Lateral raise", "Incline push-up"]
  }),
  exercise({
    name: "Lateral raise",
    muscleGroup: "shoulders",
    primaryTargets: ["shoulders"],
    secondaryTargets: [],
    equipment: "dumbbells-only",
    focus: ["push", "upper"],
    movementPattern: "isolation",
    stabilityDemand: 1,
    fatigueScore: 1,
    difficulty: 1,
    setupComplexity: 1,
    crowdingFriendliness: 5,
    jointStress: { shoulder: 2 },
    contraindications: ["shoulders"],
    saferFor: ["back"],
    substitutionGroup: "side-delt",
    hypertrophyRating: 5,
    strengthRating: 1,
    athleticRating: 1,
    setupZone: "dumbbell",
    cue: "Lead with elbows and stop around shoulder height.",
    substituteOptions: ["Lean-away wall raise", "Band lateral raise", "Landmine press"]
  }),
  exercise({
    name: "Cable triceps pressdown",
    muscleGroup: "arms",
    primaryTargets: ["arms"],
    secondaryTargets: [],
    equipment: "cable",
    focus: ["push", "upper"],
    movementPattern: "isolation",
    stabilityDemand: 1,
    fatigueScore: 1,
    difficulty: 1,
    setupComplexity: 2,
    crowdingFriendliness: 3,
    jointStress: { elbow: 1 },
    contraindications: ["arms"],
    saferFor: ["shoulders"],
    substitutionGroup: "triceps",
    hypertrophyRating: 4,
    strengthRating: 1,
    athleticRating: 1,
    setupZone: "cable",
    cue: "Pin elbows and finish with a full lockout.",
    substituteOptions: ["Close-grip push-up", "Overhead dumbbell extension", "Diamond incline push-up"]
  }),
  exercise({
    name: "Hammer curl",
    muscleGroup: "arms",
    primaryTargets: ["arms"],
    secondaryTargets: [],
    equipment: "dumbbells-only",
    focus: ["pull", "upper"],
    movementPattern: "isolation",
    stabilityDemand: 1,
    fatigueScore: 1,
    difficulty: 1,
    setupComplexity: 1,
    crowdingFriendliness: 5,
    jointStress: { elbow: 1, wrist: 1 },
    contraindications: ["arms"],
    saferFor: ["shoulders"],
    substitutionGroup: "biceps",
    hypertrophyRating: 4,
    strengthRating: 1,
    athleticRating: 1,
    setupZone: "dumbbell",
    cue: "Keep wrists neutral and lower slowly.",
    substituteOptions: ["Towel curl isometric", "Band curl", "Chin-up hold"]
  }),
  exercise({
    name: "Dead bug",
    muscleGroup: "core",
    primaryTargets: ["core"],
    secondaryTargets: [],
    equipment: "bodyweight",
    focus: ["core", "full-body"],
    movementPattern: "anti-extension",
    stabilityDemand: 2,
    fatigueScore: 1,
    difficulty: 1,
    setupComplexity: 1,
    crowdingFriendliness: 5,
    jointStress: { "lower-back": 1 },
    contraindications: [],
    saferFor: ["back", "shoulders", "legs"],
    substitutionGroup: "core-anti-extension",
    hypertrophyRating: 2,
    strengthRating: 2,
    athleticRating: 3,
    setupZone: "floor",
    cue: "Exhale, flatten ribs, and move only as far as you can control.",
    substituteOptions: ["Heel taps", "Forearm plank", "Bear plank hold"]
  }),
  exercise({
    name: "Side plank",
    muscleGroup: "core",
    primaryTargets: ["core"],
    secondaryTargets: ["shoulders"],
    equipment: "bodyweight",
    focus: ["core", "full-body"],
    movementPattern: "anti-rotation",
    stabilityDemand: 2,
    fatigueScore: 1,
    difficulty: 1,
    setupComplexity: 1,
    crowdingFriendliness: 5,
    jointStress: { shoulder: 1, "lower-back": 1 },
    contraindications: [],
    saferFor: ["back", "legs"],
    substitutionGroup: "core-anti-rotation",
    hypertrophyRating: 2,
    strengthRating: 2,
    athleticRating: 3,
    setupZone: "floor",
    cue: "Stack hips and make a straight line from head to heels.",
    substituteOptions: ["Knee side plank", "Suitcase carry", "Pallof press"]
  }),
  exercise({
    name: "Suitcase carry",
    muscleGroup: "core",
    primaryTargets: ["core"],
    secondaryTargets: ["arms", "back"],
    equipment: "dumbbells-only",
    focus: ["core", "full-body", "conditioning"],
    movementPattern: "carry",
    stabilityDemand: 3,
    fatigueScore: 2,
    difficulty: 1,
    setupComplexity: 1,
    crowdingFriendliness: 4,
    jointStress: { "lower-back": 2, shoulder: 1 },
    contraindications: ["back"],
    saferFor: ["shoulders"],
    substitutionGroup: "carry",
    hypertrophyRating: 1,
    strengthRating: 3,
    athleticRating: 5,
    setupZone: "dumbbell",
    cue: "Walk tall, keep ribs stacked, and do not let the weight pull you sideways.",
    substituteOptions: ["Side plank", "Pallof press", "Dead bug"]
  }),
  exercise({
    name: "Pallof press",
    muscleGroup: "core",
    primaryTargets: ["core"],
    secondaryTargets: [],
    equipment: "cable",
    focus: ["core", "full-body"],
    movementPattern: "anti-rotation",
    stabilityDemand: 2,
    fatigueScore: 1,
    difficulty: 1,
    setupComplexity: 2,
    crowdingFriendliness: 3,
    jointStress: { "lower-back": 1, shoulder: 1 },
    contraindications: [],
    saferFor: ["back", "shoulders"],
    substitutionGroup: "core-anti-rotation",
    hypertrophyRating: 1,
    strengthRating: 2,
    athleticRating: 4,
    setupZone: "cable",
    cue: "Press straight out and resist rotation without leaning.",
    substituteOptions: ["Side plank", "Suitcase carry", "Dead bug"]
  }),
  exercise({
    name: "Kettlebell swing",
    muscleGroup: "conditioning",
    primaryTargets: ["conditioning", "glutes"],
    secondaryTargets: ["core", "back"],
    equipment: "kettlebell",
    focus: ["conditioning", "full-body", "lower"],
    movementPattern: "power",
    stabilityDemand: 3,
    fatigueScore: 4,
    difficulty: 3,
    setupComplexity: 1,
    crowdingFriendliness: 4,
    jointStress: { "lower-back": 3, hip: 3 },
    contraindications: ["back", "glutes"],
    saferFor: [],
    substitutionGroup: "power-hinge",
    hypertrophyRating: 2,
    strengthRating: 3,
    athleticRating: 5,
    setupZone: "open-space",
    cue: "Snap hips, float the bell, and keep arms relaxed.",
    substituteOptions: ["Dumbbell hinge swing", "Hip hinge drill", "Step-up intervals"]
  }),
  exercise({
    name: "Mountain climber intervals",
    muscleGroup: "conditioning",
    primaryTargets: ["conditioning"],
    secondaryTargets: ["core", "shoulders"],
    equipment: "bodyweight",
    focus: ["conditioning", "full-body"],
    movementPattern: "conditioning",
    stabilityDemand: 2,
    fatigueScore: 3,
    difficulty: 2,
    setupComplexity: 1,
    crowdingFriendliness: 5,
    jointStress: { shoulder: 2, wrist: 2 },
    contraindications: ["shoulders"],
    saferFor: ["legs", "back"],
    substitutionGroup: "conditioning",
    hypertrophyRating: 1,
    strengthRating: 1,
    athleticRating: 3,
    setupZone: "floor",
    cue: "Move fast while keeping shoulders over wrists.",
    substituteOptions: ["Marching high knees", "Step-up intervals", "Incline mountain climber"]
  }),
  exercise({
    name: "Bike intervals",
    muscleGroup: "conditioning",
    primaryTargets: ["conditioning"],
    secondaryTargets: ["legs"],
    equipment: "machine",
    focus: ["conditioning", "full-body"],
    movementPattern: "conditioning",
    stabilityDemand: 1,
    fatigueScore: 2,
    difficulty: 1,
    setupComplexity: 1,
    crowdingFriendliness: 2,
    jointStress: { knee: 1, "lower-back": 1 },
    contraindications: [],
    saferFor: ["back", "shoulders", "legs"],
    substitutionGroup: "conditioning",
    hypertrophyRating: 1,
    strengthRating: 1,
    athleticRating: 3,
    setupZone: "machine",
    cue: "Keep posture tall and push hard only during the work interval.",
    substituteOptions: ["Marching high knees", "Step-up intervals", "Incline walk intervals"]
  })
];

export function equipmentFits(template: ExerciseTemplate, access: EquipmentAccess) {
  if (template.equipment === "bodyweight" || template.equipment === "band") return true;
  if (access === "full-gym") return true;
  if (access === "home-gym") {
    return ["dumbbells-only", "bodyweight", "kettlebell", "barbell", "band"].includes(template.equipment);
  }
  if (access === "dumbbells-only") {
    return ["dumbbells-only", "bodyweight", "band"].includes(template.equipment);
  }
  return false;
}

export function focusForWeakPoint(weakPoint: WeakPoint): BodyFocus {
  if (weakPoint === "legs" || weakPoint === "glutes") return "lower";
  if (weakPoint === "conditioning") return "conditioning";
  if (weakPoint === "core") return "core";
  if (weakPoint === "back" || weakPoint === "arms") return "pull";
  return "push";
}
